import Head from "next/head";
import { useState } from "react";
import Cssedit from "../components/editors/cssedit";
import Htmledit from "../components/editors/htmledit";
import Jsedit from "../components/editors/jsedit";
import Navbar from "../components/Navbar";
import Sidebar from "../components/sidebar";

export default function Home() {
  const [html, setHtml] = useState("<h1>Hello world!!!</h1>");
  const [css, setCss] = useState("body{background: white;}");
  const [js, setJs] = useState("const var = 10;");

  const [isHtml, setIsHtml] = useState(false);
  const [isCss, setIsCss] = useState(false);
  const [isJs, setIsJs] = useState(true);

  const srcDoc = `
    <html>
    <body>${html}</body>
    <style>${css}</style>
    <script>${js}</script>
    </html>
  `;
  return (
    <>
      <Head>
        <title>Online code editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-editor">
        <Navbar />
        <div className="full-editor">
          <div className="main-sec">
            <Sidebar />
          </div>
          <div className="editor-sec">
            {isHtml == true ? (
              <Htmledit value={html} onChange={setHtml} />
            ) : null}
            {isCss == true ? <Cssedit value={css} onChange={setCss} /> : null}
            {isJs == true ? <Jsedit value={js} onChange={setJs} /> : null}

            {/* <Cssedit  value={css} onChange={setCss} />
            <Jsedit  value={js} onChange={setJs} /> */}
          </div>
          <div className="preview-sec">
            <iframe
              srcDoc={srcDoc}
              title="output"
              sandbox="allow-scripts"
              width="100%"
              height="100%"
            />
          </div>
        </div>
      </div>
    </>
  );
}
