import Head from "next/head";
import { useState, useContext, useEffect } from "react";
import Cssedit from "../components/editors/cssedit";
import Htmledit from "../components/editors/htmledit";
import Jsedit from "../components/editors/jsedit";
import Navbar from "../components/Navbar";
import Sidebar from "../components/sidebar";
import { ClickContext } from "../contexts/clickContext";

export default function Home() {
  const { isCss, isHtml, isJs, html, setHtml, css, setCss, js, setJs } =
    useContext(ClickContext);

  const [srcDoc, setSrcDoc] = useState(``);

  useEffect(() => {
    const timeout = setTimeout(() => {
      setSrcDoc(`
          <html>
          <body>${html}</body>
          <style>${css}</style>
          <script>${js}</script>
          </html>
        `);
    }, 300);
    return () => clearTimeout(timeout);
  }, [html, css, js]);

  return (
    <>
      <Head>
        <title>Online code editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="./apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="./favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="./favicon-16x16.png"
        />
        <link rel="manifest" href="./site.webmanifest" />
      </Head>

      <div className="main-editor">
        <Navbar />
        <div className="full-editor">
          <div className="main-sec">
            <Sidebar />
          </div>
          <div className="editor-sec">
            {isHtml == true ? (
              <Htmledit value={html} onChange={setHtml} />
            ) : null}
            {isCss == true ? <Cssedit value={css} onChange={setCss} /> : null}
            {isJs == true ? <Jsedit value={js} onChange={setJs} /> : null}
          </div>
          <div className="preview-sec">
            <iframe
              srcDoc={srcDoc}
              title="output"
              sandbox="allow-scripts"
              width="100%"
              height="100%"
            />
          </div>
        </div>
      </div>
    </>
  );
}
